### ISSUE TITLE
🔑 Feature: Forget password

### ISSUE THREAD

**Issue by nyomansunima** [sonibble/woy#16]
### Tasks

- [x] Create the forget password form
- [ ] Reset password token passed into email that is related
- [ ] Identify the token and reset the password with the new one
- [ ] Bring back user to login

**Comment by nyomansunima** [comment]
Now, the fronend are finished, Move into backend to send email code verification
